### PR TITLE
#414 - Make relpath work in 0.7

### LINKED ISSUE #414: relpath macro does not work in v0.7
Starting with v0.7, when using `@relpath` from outside the `Reachability` module, Julia still looks inside the `Reachability` module.

### PR DESCRIPTION
**Pull request by mforets**
Closes #414.

### CODE REVIEW

File: src/Utils/Utils.jl [hunk 1]
```diff
@@ -265,21 +265,65 @@ function add_plot_labels(plot_vars::Vector{Int64};
...
+
+```julia
+# file /home/projects/P1/s.jl
+d = open(@relpath "x.dat")
+# do stuff with d
+```
+In this example, the macro `@relpath "s.jl"` evaluates to the string
+`/home/projects/P1/x.dat`. The script `s.jl` can be evaluated from the command line
+from any folder, e.g. suppose that the path working directory is `/home/projects`,
+then one can do `$ julia -e 'include("P1/s.jl")'` without having to change `a.jl`.
```
Comment (mforets) [inline src/Utils/Utils.jl]:
```suggestion
then one can do `$ julia -e 'include("P1/s.jl")'` without having to change `s.jl`.
```

File: src/Utils/Utils.jl [hunk 2]
```diff
@@ -265,21 +265,65 @@ function add_plot_labels(plot_vars::Vector{Int64};
...
+
+```julia
+# file /home/projects/P1/s.jl
+d = open(@relpath "x.dat")
+# do stuff with d
+```
+In this example, the macro `@relpath "s.jl"` evaluates to the string
+`/home/projects/P1/x.dat`. The script `s.jl` can be evaluated from the command line
+from any folder, e.g. suppose that the path working directory is `/home/projects`,
+then one can do `$ julia -e 'include("P1/s.jl")'` without having to change `s.jl`.
```
Comment (mforets) [inline src/Utils/Utils.jl]:
```suggestion
then one can do `julia -e 'include("P1/s.jl")'` without having to change `s.jl`.
```

Comment (mforets) [reply src/Utils/Utils.jl]: (i had to remove the `$` in `$ julia . . .` because otherwise it gives a 

```julia
[ Info: Precompiling Reachability [774a0091-654f-5c65-bbdc-ad5b67b45832]
ERROR: LoadError: LoadError: syntax: invalid interpolation syntax: "$ "
```

File: src/Utils/Utils.jl [hunk 3]
```diff
@@ -265,21 +265,65 @@ function add_plot_labels(plot_vars::Vector{Int64};
     return labels
 end
 
+@static if VERSION >= v"0.7"
+    @eval begin
```
Comment (schillic) [inline src/Utils/Utils.jl]: Is this extra block necessary?

Comment (mforets) [reply src/Utils/Utils.jl]: it seems to work without it 👍
