### PR TITLE
#150 - Default partition

### LINKED ISSUE #150: Default partition
This is to handle a case like:

```julia
julia> p = InitialValueProblem(LinearContinuousSystem(randn(4, 4)), BallInf(ones(4), 0.1));

julia> s = solve(p, :T=>0.1, :vars=>[1,3]);
ERROR: need option :partition specified
Stacktrace:
 [1] check_and_add_partition_block_types!(::Dict{Symbol,Any}, ::Dict{Symbol,Any}) at /Users/forets/.julia/v0.6/Reachability/src/options.jl:478
 [2] validate_solver_options_and_add_default_values!(::Reachability.Options) at /Users/forets/.julia/v0.6/Reachability/src/options.jl:164
 [3] solve(::Systems.InitialValueProblem{Systems.LinearContinuousSystem{Float64,Array{Float64,2}},LazySets.BallInf{Float64}}, ::Reachability.Options) at /Users/forets/.julia/v0.6/Reachability/src/solve.jl:92
 [4] solve(::Systems.InitialValueProblem{Systems.LinearContinuousSystem{Float64,Array{Float64,2}},LazySets.BallInf{Float64}}, ::Pair{Symbol,Float64}, ::Pair{Symbol,Array{Int64,1}}, ::Vararg{Pair{Symbol,Array{Int
64,1}},N} where N) at /Users/forets/.julia/v0.6/Reachability/src/solve.jl:227
```

proposal: use `Intervals` as default for the `partition` (should also define `block_types`).

See also #92 for better sanity checks related to this option.

### PR DESCRIPTION
**Pull request by mforets**
Closes #150.

### CODE REVIEW

File: src/options.jl [hunk 1]
```diff
@@ -425,8 +425,21 @@ function check_and_add_approximation!(dict::Dict{Symbol,Any},
...
-    set_type = haskey(dict, :set_type) ? dict[:set_type] :
-        (ε < Inf ? HPolygon : Hyperrectangle)
+
+    if haskey(dict, :set_type)
+        set_type = dict[:set_type]
+    else
+        if ε < Inf
+            set_type = HPolygon
+        else
+            if !haskey(dict, :partition)
```
Comment (schillic) [inline src/options.jl]: Merge `else` and `if`?

File: src/options.jl [hunk 2]
```diff
@@ -475,7 +488,9 @@ function check_and_add_partition_block_types!(dict::Dict{Symbol,Any},
     check_aliases!(dict, dict_copy, [:partition])
     if !haskey(dict_copy, :partition)
         # TODO allow partial information and infer the other (also with :vars)
```
Comment (schillic) [inline src/options.jl]: This can be removed now (I think).
There is also an empty line below.

File: src/options.jl (hunk 1 above)
Comment (mforets) [reply src/options.jl]: could be merged, but i kept the branch `ε = Inf` below because it is conceptually different:

```julia
        if ε < Inf
            set_type = HPolygon
        else
            # do not support iterative refinement => ignore ε
            if !haskey(dict, :partition)
                set_type = Interval
                set_type_proj = Interval
            else
                set_type = Hyperrectangle
            end
        end
```
